import type { DestinationType } from "@/lib/types";

/**
 * Dummy catalog of Indian vacation spots used to seed preference pickers and
 * demo content. Not wired to the Gemini scoring pipeline — that reasons over
 * free-form destination types and dealbreakers, not this list.
 */
export type IndiaDestination = {
  id: string;
  name: string;
  state: string;
  types: DestinationType[];
  description: string;
  image: string;
};

export const INDIA_DESTINATIONS: IndiaDestination[] = [
  {
    id: "goa",
    name: "Goa",
    state: "Goa",
    types: ["beach", "relaxation"],
    description: "Palm-lined beaches, beach shacks, and a laid-back party scene.",
    image: "https://picsum.photos/id/1011/800/1000",
  },
  {
    id: "manali",
    name: "Manali",
    state: "Himachal Pradesh",
    types: ["mountain", "adventure"],
    description: "Snow-capped peaks, pine forests, and easy access to trekking and paragliding.",
    image: "https://picsum.photos/id/1015/800/1000",
  },
  {
    id: "leh-ladakh",
    name: "Leh-Ladakh",
    state: "Ladakh",
    types: ["mountain", "adventure", "nature"],
    description: "High-altitude desert, monasteries, and dramatic mountain passes.",
    image: "https://picsum.photos/id/1016/800/1000",
  },
  {
    id: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    types: ["city"],
    description: "The Pink City — forts, palaces, and bazaars.",
    image: "https://picsum.photos/id/1018/800/1000",
  },
  {
    id: "udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    types: ["city", "relaxation"],
    description: "Lakeside palaces and romantic old-city views.",
    image: "https://picsum.photos/id/1020/800/1000",
  },
  {
    id: "jodhpur",
    name: "Jodhpur",
    state: "Rajasthan",
    types: ["city"],
    description: "The Blue City, dominated by Mehrangarh Fort.",
    image: "https://picsum.photos/id/1024/800/1000",
  },
  {
    id: "kerala-backwaters",
    name: "Alleppey (Kerala Backwaters)",
    state: "Kerala",
    types: ["nature", "relaxation"],
    description: "Houseboat cruises through palm-fringed backwaters.",
    image: "https://picsum.photos/id/1025/800/1000",
  },
  {
    id: "munnar",
    name: "Munnar",
    state: "Kerala",
    types: ["mountain", "nature", "relaxation"],
    description: "Rolling tea plantations and misty hill views.",
    image: "https://picsum.photos/id/1027/800/1000",
  },
  {
    id: "rishikesh",
    name: "Rishikesh",
    state: "Uttarakhand",
    types: ["adventure", "nature"],
    description: "White-water rafting, yoga ashrams, and the Ganges.",
    image: "https://picsum.photos/id/1028/800/1000",
  },
  {
    id: "andaman",
    name: "Andaman Islands",
    state: "Andaman & Nicobar",
    types: ["beach", "adventure", "relaxation"],
    description: "Turquoise water, coral reefs, and quiet white-sand beaches.",
    image: "https://picsum.photos/id/1029/800/1000",
  },
  {
    id: "varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    types: ["city"],
    description: "Ancient ghats along the Ganges and centuries of ritual life.",
    image: "https://picsum.photos/id/1031/800/1000",
  },
  {
    id: "agra",
    name: "Agra",
    state: "Uttar Pradesh",
    types: ["city"],
    description: "Home to the Taj Mahal and Mughal-era architecture.",
    image: "https://picsum.photos/id/1035/800/1000",
  },
  {
    id: "darjeeling",
    name: "Darjeeling",
    state: "West Bengal",
    types: ["mountain", "relaxation"],
    description: "Tea gardens and Himalayan sunrise views from Tiger Hill.",
    image: "https://picsum.photos/id/1036/800/1000",
  },
  {
    id: "gangtok",
    name: "Gangtok",
    state: "Sikkim",
    types: ["mountain", "nature"],
    description: "Monasteries and views of Kanchenjunga.",
    image: "https://picsum.photos/id/1039/800/1000",
  },
  {
    id: "shillong",
    name: "Shillong",
    state: "Meghalaya",
    types: ["nature", "adventure"],
    description: "Waterfalls, living root bridges, and rolling hills.",
    image: "https://picsum.photos/id/1043/800/1000",
  },
  {
    id: "coorg",
    name: "Coorg",
    state: "Karnataka",
    types: ["nature", "relaxation"],
    description: "Coffee plantations and misty Western Ghats scenery.",
    image: "https://picsum.photos/id/1045/800/1000",
  },
  {
    id: "hampi",
    name: "Hampi",
    state: "Karnataka",
    types: ["adventure", "city"],
    description: "Boulder-strewn ruins of the Vijayanagara Empire.",
    image: "https://picsum.photos/id/1047/800/1000",
  },
  {
    id: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    types: ["city"],
    description: "Coastal metropolis with nightlife, food, and film culture.",
    image: "https://picsum.photos/id/1048/800/1000",
  },
  {
    id: "pondicherry",
    name: "Pondicherry",
    state: "Puducherry",
    types: ["beach", "relaxation", "city"],
    description: "French Quarter streets and quiet promenade beaches.",
    image: "https://picsum.photos/id/1050/800/1000",
  },
  {
    id: "gokarna",
    name: "Gokarna",
    state: "Karnataka",
    types: ["beach", "relaxation"],
    description: "Quieter, cliffside alternative to Goa's beaches.",
    image: "https://picsum.photos/id/1053/800/1000",
  },
  {
    id: "ranthambore",
    name: "Ranthambore",
    state: "Rajasthan",
    types: ["nature", "adventure"],
    description: "Tiger safaris around a historic fort.",
    image: "https://picsum.photos/id/1056/800/1000",
  },
  {
    id: "spiti-valley",
    name: "Spiti Valley",
    state: "Himachal Pradesh",
    types: ["mountain", "adventure", "nature"],
    description: "Remote high-altitude desert valley and ancient monasteries.",
    image: "https://picsum.photos/id/1058/800/1000",
  },
  {
    id: "mysore",
    name: "Mysore",
    state: "Karnataka",
    types: ["city", "relaxation"],
    description: "Grand palaces and a laid-back pace compared to Bengaluru.",
    image: "https://picsum.photos/id/1060/800/1000",
  },
  {
    id: "kodaikanal",
    name: "Kodaikanal",
    state: "Tamil Nadu",
    types: ["mountain", "relaxation", "nature"],
    description: "A cool hill-station retreat with a placid lake.",
    image: "https://picsum.photos/id/1062/800/1000",
  },
  {
    id: "kasol",
    name: "Kasol",
    state: "Himachal Pradesh",
    types: ["mountain", "adventure"],
    description: "Backpacker village in the Parvati Valley, gateway to treks.",
    image: "https://picsum.photos/id/1067/800/1000",
  },
  {
    id: "amritsar",
    name: "Amritsar",
    state: "Punjab",
    types: ["city"],
    description: "The Golden Temple and the Wagah border ceremony.",
    image: "https://picsum.photos/id/1069/800/1000",
  },
  {
    id: "rann-of-kutch",
    name: "Rann of Kutch",
    state: "Gujarat",
    types: ["nature", "adventure"],
    description: "Vast white salt desert, especially striking under a full moon.",
    image: "https://picsum.photos/id/1074/800/1000",
  },
  {
    id: "lakshadweep",
    name: "Lakshadweep",
    state: "Lakshadweep",
    types: ["beach", "relaxation", "adventure"],
    description: "Coral atolls and some of India's clearest lagoon water.",
    image: "https://picsum.photos/id/1080/800/1000",
  },
  {
    id: "ooty",
    name: "Ooty",
    state: "Tamil Nadu",
    types: ["mountain", "relaxation"],
    description: "Tea estates and a toy train through the Nilgiris.",
    image: "https://picsum.photos/id/1084/800/1000",
  },
  {
    id: "khajuraho",
    name: "Khajuraho",
    state: "Madhya Pradesh",
    types: ["city", "nature"],
    description: "Intricately carved medieval temples set among open lawns.",
    image: "https://picsum.photos/id/103/800/1000",
  },
];
